// Gradle Build Configuration File generated by gradle 'init' task

plugins {
    application
}

application {
    // Define the main class for the application.
    mainClass.set("com.notestudios.main.Game")
}

repositories {
    mavenCentral()
}

dependencies {
    // This dependency is used by the application.
    implementation("com.google.guava:guava:33.0.0-jre")
    // Game Libraries
    implementation(files("libs/discord-rpc.jar", "libs/GJAPI.jar", "libs/JSONutils.jar"))
}

sourceSets {
    main {
       java {
          srcDirs("src", "assets")
       }
    }
}


tasks.withType<Jar> {
    manifest {
        attributes["Main-Class"] = "com.notestudios.main.Game"
    }
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
    targetCompatibility = JavaVersion.VERSION_1_8
}
