name: Check source code

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Set up Temurin OpenJDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Set up Gradle 8.5
      uses: gradle/gradle-build-action@v2.11.1
      id: setup-gradle

    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2.11.1
      with:
        arguments: --debug jar

    - name: Upload artifact
      uses: actions/upload-artifact@v4.2.0
      with:
        name: Build-jar
        path: build/libs/TheTraveler.jar
