name: Check source code

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Set up Temurin OpenJDK 8
      uses: actions/setup-java@v4
      with:
        java-version: '8'
        distribution: 'temurin'
    
    - name: Set up Gradle 8.5
      uses: gradle/gradle-build-action@v2
      id: setup-gradle
      with:
        gradle-version: 8.5
    
    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with: 
        arguments: --stacktrace build
        gradle-version: 8.5
      
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Check source code
      uses: gradle/gradle-build-action@v2
      with: 
        arguments: --stacktrace check
        gradle-version: 8.5
          
