name: Check source code

permissions:
  contents: read

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
    - name: Set up Gradle 8.5
      uses: gradle/actions/setup-gradle@v0
    - name: Build with Gradle
      run: ./gradlew build
    - name: Checkout
      uses: actions/checkout@v3
    - name: Check source code
      run: ./gradlew --verbose check
